package org.techas.falleaves.utils;

public enum HttpCode {

    // Common

    COMMON__SUCCESS(200, 0),
    COMMON__INTERNET_SERVER_ERROR(500, 0),
    COMMON__BEHAVIOR_VALID_FAILED(401, 100),

    // Auth

        // Login

        AUTH_LOGIN__IDENTIFIER_EMPTY(401, 100),
        AUTH_LOGIN__CREDENTIAL_EMPTY(401, 101),

        AUTH_LOGIN__ACCOUNT_NOT_EXISTS(401, 102),
        AUTH_LOGIN__ACCOUNT_LOCKED(401, 103),
        AUTH_LOGIN__ACCOUNT_DISABLED(401, 104),
        AUTH_LOGIN__INCORRECT_CREDENTIALS(401, 105),


        // Register
        AUTH_REGISTER__NICKNAME_EMPTY(401, 200),
        AUTH_REGISTER__EMAIL_EMPTY(401, 201),
        AUTH_REGISTER__EMAIL_VALID_EMPTY(401, 202),
        AUTH_REGISTER__PASSWORD_EMPTY(401, 203),
        AUTH_REGISTER__PASSWORD2_EMPTY(401, 204),

        AUTH_REGISTER__NICKNAME_REGEX_FAILED(401, 205),
        AUTH_REGISTER__NICKNAME_EXISTS(401, 206),
        AUTH_REGISTER__REGEX_EMAIL_FAILED(401, 207),
        AUTH_REGISTER__EMAIL_EXISTS(401, 208),
        AUTH_REGISTER__PASSWORD_REGEX_FAILED(401, 209),
        AUTH_REGISTER__TWO_PASSWORD_NOTMATCH(401, 210),
        AUTH_REGISTER__EMAIL_VALID_FAILED(401, 211),


        // Register Mail
        AUTH_REGISTER_MAIL__EMAIL_EMPTY(401, 300),
        AUTH_REGISTER_MAIL__EMAIL_REGEX_FAILED(401, 301),
        AUTH_REGISTER_MAIL__EMAIL_EXISTS(401, 302),
        AUTH_REGISTER_MAIL__MAIL_REQUEST_FREQUENTLY(401, 303),

        // Forget Password
        AUTH_FORGETPASSWORD__EMAIL_EMPTY(401, 400),
        AUTH_FORGETPASSWORD__EMAIL_NOT_EXISTS(401, 401),

        // Set Password
        AUTH_SETPASSWORD__DATA_EMPTY(401, 500),
        AUTH_SETPASSWORD__DATA_EXCEPT(401, 501),
        AUTH_SETPASSWORD__EXPIRE(401, 502),


        // Behavior Valid
        BEHAVIOR_VALID__FAILED(401, 800),
        BEHAVIOR_VALID__COMMON_FAILED(401, 801),

        // Manager

            // User
            MANAGER_USER__USER_ID_EMPTY(401, 1000),
            MANAGER_USER__STATUS_EMPTY(401, 1001),
            MANAGER_USER__USER_ID_NOT_EXISTS(401, 1002),

    ;

    public int codeType;
    public int codeAppend;

    HttpCode(int codeType, int codeAppend) {
        this.codeType = codeType;
        this.codeAppend = codeAppend;
    }
}